generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: ping-secrets
    namespace: simple-ping-application--master
    literals:
      - PING_SERVICE__APP_LOG_PATH=logs/app.log
      - PING_SERVICE__HOSTS=google.com
      - PING_SERVICE__ICMP_DELAY=5000
      - PING_SERVICE__REPORT_URL=https://www.postb.in/1732320982251-4400979713536t
      - PING_SERVICE__TCP_DELAY=5000
      - PING_SERVICE__TCP_PING_PORT_END_POINT=:46031/health/200ok
      - PING_SERVICE__TCP_PROTOCOL=https
      - PING_SERVICE__TCP_TIMEOUT=3000
      - PING_SERVICE__TRACEROUTE_DELAY=5000
